version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/site" # Location of package manifests
    schedule:
      interval: "daily"
    assignees:
      - "Ti1mmy"
    labels:
      - "website"
      - "dependencies"
